# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_TrackMaster.ui'
#
# Created: Thu Sep 29 18:03:04 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_TrackMasterApp(object):
    def setupUi(self, TrackMasterApp):
        TrackMasterApp.setObjectName("TrackMasterApp")
        TrackMasterApp.resize(1114, 853)
        TrackMasterApp.setStyleSheet("#Form{background-color: rgb(0, 0, 0);}")
        self.verticalLayout = QtGui.QVBoxLayout(TrackMasterApp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_label = QtGui.QLabel(TrackMasterApp)
        self.header_label.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setFamily("Myriad Arabic")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.header_label.setFont(font)
        self.header_label.setAutoFillBackground(False)
        self.header_label.setStyleSheet("background-color: rgb(149, 0, 2);\n"
"color: rgb(255, 255, 255);")
        self.header_label.setObjectName("header_label")
        self.verticalLayout.addWidget(self.header_label)
        self.scrollArea = QtGui.QScrollArea(TrackMasterApp)
        self.scrollArea.setStyleSheet("#scrollArea{    background-color: rgb(0, 0, 0);}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1077, 788))
        self.scrollAreaWidgetContents.setStyleSheet("#scrollAreaWidgetContents{\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(14)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TrackController = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.TrackController.setMinimumSize(QtCore.QSize(0, 50))
        self.TrackController.setMaximumSize(QtCore.QSize(16777215, 50))
        self.TrackController.setObjectName("TrackController")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.TrackController)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_34 = QtGui.QPushButton(self.TrackController)
        self.pushButton_34.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_34.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_34.setObjectName("pushButton_34")
        self.horizontalLayout_7.addWidget(self.pushButton_34)
        self.label_8 = QtGui.QLabel(self.TrackController)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lineEdit = QtGui.QLineEdit(self.TrackController)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.textEdit = QtGui.QTextEdit(self.TrackController)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_7.addWidget(self.textEdit)
        self.verticalLayout_4.addWidget(self.TrackController)
        self.widget_2 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton = QtGui.QPushButton(self.widget_2)
        self.pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.label_10 = QtGui.QLabel(self.widget_2)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.lineEdit_2 = QtGui.QLineEdit(self.widget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        self.textEdit_2 = QtGui.QTextEdit(self.widget_2)
        self.textEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_8.addWidget(self.textEdit_2)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_32 = QtGui.QPushButton(self.widget_3)
        self.pushButton_32.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_32.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_32.setObjectName("pushButton_32")
        self.horizontalLayout_9.addWidget(self.pushButton_32)
        self.label_18 = QtGui.QLabel(self.widget_3)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.lineEdit_3 = QtGui.QLineEdit(self.widget_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_9.addWidget(self.lineEdit_3)
        self.textEdit_3 = QtGui.QTextEdit(self.widget_3)
        self.textEdit_3.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_9.addWidget(self.textEdit_3)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget_4 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_33 = QtGui.QPushButton(self.widget_4)
        self.pushButton_33.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_33.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_10.addWidget(self.pushButton_33)
        self.label_11 = QtGui.QLabel(self.widget_4)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.lineEdit_4 = QtGui.QLineEdit(self.widget_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_10.addWidget(self.lineEdit_4)
        self.textEdit_4 = QtGui.QTextEdit(self.widget_4)
        self.textEdit_4.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_10.addWidget(self.textEdit_4)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.widget_5 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_35 = QtGui.QPushButton(self.widget_5)
        self.pushButton_35.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_35.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_35.setObjectName("pushButton_35")
        self.horizontalLayout_11.addWidget(self.pushButton_35)
        self.label_20 = QtGui.QLabel(self.widget_5)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.lineEdit_5 = QtGui.QLineEdit(self.widget_5)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_11.addWidget(self.lineEdit_5)
        self.textEdit_5 = QtGui.QTextEdit(self.widget_5)
        self.textEdit_5.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_5.setObjectName("textEdit_5")
        self.horizontalLayout_11.addWidget(self.textEdit_5)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_6 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_42 = QtGui.QPushButton(self.widget_6)
        self.pushButton_42.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_42.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_12.addWidget(self.pushButton_42)
        self.label_19 = QtGui.QLabel(self.widget_6)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.lineEdit_6 = QtGui.QLineEdit(self.widget_6)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_12.addWidget(self.lineEdit_6)
        self.textEdit_6 = QtGui.QTextEdit(self.widget_6)
        self.textEdit_6.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_6.setObjectName("textEdit_6")
        self.horizontalLayout_12.addWidget(self.textEdit_6)
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_12 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.widget_12)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton_48 = QtGui.QPushButton(self.widget_12)
        self.pushButton_48.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_48.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_48.setObjectName("pushButton_48")
        self.horizontalLayout_18.addWidget(self.pushButton_48)
        self.label_27 = QtGui.QLabel(self.widget_12)
        self.label_27.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_18.addWidget(self.label_27)
        self.lineEdit_12 = QtGui.QLineEdit(self.widget_12)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_18.addWidget(self.lineEdit_12)
        self.textEdit_12 = QtGui.QTextEdit(self.widget_12)
        self.textEdit_12.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_12.setObjectName("textEdit_12")
        self.horizontalLayout_18.addWidget(self.textEdit_12)
        self.verticalLayout_4.addWidget(self.widget_12)
        self.widget_11 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.widget_11)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.pushButton_47 = QtGui.QPushButton(self.widget_11)
        self.pushButton_47.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_47.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_47.setObjectName("pushButton_47")
        self.horizontalLayout_22.addWidget(self.pushButton_47)
        self.label_26 = QtGui.QLabel(self.widget_11)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_22.addWidget(self.label_26)
        self.lineEdit_11 = QtGui.QLineEdit(self.widget_11)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_22.addWidget(self.lineEdit_11)
        self.textEdit_11 = QtGui.QTextEdit(self.widget_11)
        self.textEdit_11.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_11.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_11.setObjectName("textEdit_11")
        self.horizontalLayout_22.addWidget(self.textEdit_11)
        self.verticalLayout_4.addWidget(self.widget_11)
        self.widget_10 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.widget_10)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pushButton_45 = QtGui.QPushButton(self.widget_10)
        self.pushButton_45.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_45.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_45.setObjectName("pushButton_45")
        self.horizontalLayout_20.addWidget(self.pushButton_45)
        self.label_25 = QtGui.QLabel(self.widget_10)
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_20.addWidget(self.label_25)
        self.lineEdit_10 = QtGui.QLineEdit(self.widget_10)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_20.addWidget(self.lineEdit_10)
        self.textEdit_10 = QtGui.QTextEdit(self.widget_10)
        self.textEdit_10.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_10.setObjectName("textEdit_10")
        self.horizontalLayout_20.addWidget(self.textEdit_10)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.widget_8 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.widget_8)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_43 = QtGui.QPushButton(self.widget_8)
        self.pushButton_43.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_43.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_17.addWidget(self.pushButton_43)
        self.label_23 = QtGui.QLabel(self.widget_8)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_17.addWidget(self.label_23)
        self.lineEdit_8 = QtGui.QLineEdit(self.widget_8)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_17.addWidget(self.lineEdit_8)
        self.textEdit_8 = QtGui.QTextEdit(self.widget_8)
        self.textEdit_8.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_8.setObjectName("textEdit_8")
        self.horizontalLayout_17.addWidget(self.textEdit_8)
        self.verticalLayout_4.addWidget(self.widget_8)
        self.widget_9 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.widget_9)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_46 = QtGui.QPushButton(self.widget_9)
        self.pushButton_46.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_46.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_46.setObjectName("pushButton_46")
        self.horizontalLayout_21.addWidget(self.pushButton_46)
        self.label_24 = QtGui.QLabel(self.widget_9)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_21.addWidget(self.label_24)
        self.lineEdit_9 = QtGui.QLineEdit(self.widget_9)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_21.addWidget(self.lineEdit_9)
        self.textEdit_9 = QtGui.QTextEdit(self.widget_9)
        self.textEdit_9.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_9.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_9.setObjectName("textEdit_9")
        self.horizontalLayout_21.addWidget(self.textEdit_9)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.widget_7 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.widget_7)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_44 = QtGui.QPushButton(self.widget_7)
        self.pushButton_44.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_44.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_44.setObjectName("pushButton_44")
        self.horizontalLayout_19.addWidget(self.pushButton_44)
        self.label_22 = QtGui.QLabel(self.widget_7)
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_19.addWidget(self.label_22)
        self.lineEdit_7 = QtGui.QLineEdit(self.widget_7)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_19.addWidget(self.lineEdit_7)
        self.textEdit_7 = QtGui.QTextEdit(self.widget_7)
        self.textEdit_7.setMinimumSize(QtCore.QSize(0, 40))
        self.textEdit_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_7.setObjectName("textEdit_7")
        self.horizontalLayout_19.addWidget(self.textEdit_7)
        self.verticalLayout_4.addWidget(self.widget_7)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(TrackMasterApp)
        QtCore.QMetaObject.connectSlotsByName(TrackMasterApp)

    def retranslateUi(self, TrackMasterApp):
        TrackMasterApp.setWindowTitle(QtGui.QApplication.translate("TrackMasterApp", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.header_label.setText(QtGui.QApplication.translate("TrackMasterApp", "  TRACK MASTER", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_34.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_32.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_33.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_35.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_42.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_48.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_47.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_45.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_43.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_46.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_44.setText(QtGui.QApplication.translate("TrackMasterApp", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("TrackMasterApp", "01 Drumkit  Jdella 100 beats .wav 44100Hz 16bit 4:21\n"
"", None, QtGui.QApplication.UnicodeUTF8))

